---
name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - name: clone the plugin repo
        uses: actions/checkout@v2
      - name: Setup asdf and run test
        run: |
          git clone https://github.com/asdf-vm/asdf.git $HOME/asdf
          . $HOME/asdf/asdf.sh
          asdf plugin-add pulumi ./
          asdf plugin-test pulumi ./ 'pulumi version' --asdf-tool-version 1.5.2
          asdf plugin-test pulumi ./ 'pulumi version' --asdf-tool-version 1.14.0
        shell: bash
